name: drift_duckdb
description: A drift database implementation for DuckDB, allowing you to use DuckDB as a backend for drift.
version: 0.0.1
repository: https://github.com/Hu-Wentao/drift_duckdb
topics: 
 - drift
 - database
 - duckdb

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  dart_duckdb: ^1.4.4
    # git:
    #   url: https://github.com/yharby/duckdb-dart.git
    #   ref: main
  drift: ^2.31.0

dev_dependencies:
  build_runner: ^2.11.1
  drift_dev: ^2.31.0
  lints: ^6.0.0
  test: ^1.25.6
